<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/5
 * Time: 11:21
 */
namespace app\agency_admin\controller;
use think\Db;
use think\Session;
use think\Request;
use think\Loader;
use app\common\controller\simple_html_dom;
class Article extends Common
{
    protected $AgencyMemberID='';
    protected $AgencyMemberName='';
    protected $AgencyMemberInfo=array();
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->AgencyMemberInfo=Db::name('member')->where('MemberID',$this->AgencyMemberID)->find();
        $this->assign('AgencyMemberInfo',$this->AgencyMemberInfo);
        $this->assign('AgencyMemberID',$this->AgencyMemberID);
        $this->assign('AgencyMemberName',$this->AgencyMemberName);
		$this->assign('MediaWebNameID',GetCurrentWholeType(18));//	频道类型
        $this->assign('MediaIndustryID',GetCurrentWholeType(35));//综合门户媒体
        $this->assign('MediaCityID',GetCityTypeList('0'));//覆盖区域
        $this->assign('MediaInLevelID',GetCurrentWholeType(110));//入口级别
        $this->assign('MediaUrlTypeID',GetCurrentWholeType(59));//链接类型
        $this->assign('MediaSpeedID',GetCurrentWholeType(66));//发稿速度
        $this->assign('MediaNewsSourceID',GetCurrentWholeType(73));//新闻源
        $this->assign('MediaCanSendID',GetCurrentWholeType(76));//周末可发
        $this->assign('MediaSpecialIndustryID',GetCurrentWholeType(79));//特别行业
        $this->assign('MediaSituationID',GetCurrentWholeType(85));//收录情况
        $this->assign('MediaComputerWeightID',GetCurrentWholeType(88));//电脑权重
        $this->assign('MediaMobileWeightID',GetCurrentWholeType(99));//移动权重
		$this->assign('MediaMobileWeightID',GetCurrentWholeType(99));//移动权重
		$this->assign('MediaPrice',MpriceNum());//媒体价格
    }
    /**
     * 发布广告首页
     */
    public function index()
    {
        Session::set('filename','');
        $editorValue = input('editorValue');
        $beizhu =   input('beizhu');
        $title =  input('title');
        $State = input('State');
		$article_customer =   input('article_customer');
		$starttime =   input('starttime');
        $ID = input('ID');
        if(!empty($State) && $State=='Yes'){
            $ArticleInfo=db('article')->where('article_id',$ID)->where('member_id',$this->AgencyMemberID)->find();
			$OrderInfo=db('agencyorder')->where('article_id',$ID)->where('media_type','2')->find();
            $title = $ArticleInfo['article_title'];
            $beizhu = $ArticleInfo['article_remarks'];
			$article_customer = $ArticleInfo['article_customer'];
			if(!empty($OrderInfo['starttime'])){
			  $starttime = date("Y-m-d",$OrderInfo['starttime']);
			}else{
				 $starttime ='';
			}
            $editorValue = $ArticleInfo['article_content'];
            Session::set('filename',$ArticleInfo['article_doc']);
            $FileName=$ArticleInfo['article_doc'];
        }

        $this->assign('editorValue',$editorValue);
        $this->assign('beizhu',$beizhu);
        $this->assign('title',$title);
		$this->assign('article_customer',$article_customer);
		$this->assign('starttime',$starttime);
        $this->assign('MemberAgentBalanceCount',$this->AgencyMemberInfo['MemberAgentBalanceCount']);
        $MainConfig=db('config')->where('MemberID','-1')->find();
        $this->assign('MainConfig',$MainConfig);
        return view();
    }
    /**
     * 发布广告媒体页
     */
    public function media()
    {
        $TempArticleID = input('TempArticleID','','trim');
        $title = input('title');
        $beizhu = input('beizhu');
        $editorValue = input('content_desc');
        $State = input('State');
		$article_customer =   input('article_customer');
		$starttime=strtotime(input('starttime'));

		if(!empty($starttime) && intval($starttime)>0){

			if(!$starttime) $this->error('请选择推送时间');
			$endtime=strtotime(date("Y-m-d 00:00",time()));//当前时间
			if($starttime < $endtime) $this->error('推送时间不能小于等于当前时间');
		}

        $ID = input('ID');
        if(!empty($State) && $State=='Yes'){
            $ArticleInfo=db('article')->where('article_id',$ID)->where('member_id',$this->AgencyMemberID)->find();
            $title = $ArticleInfo['article_title'];
            $beizhu = $ArticleInfo['article_remarks'];
			$article_customer = $ArticleInfo['article_customer'];
            $editorValue = $ArticleInfo['article_content'];
            Session::set('filename',$ArticleInfo['article_doc']);
            $FileName=$ArticleInfo['article_doc'];
        }else{
            $FileName=Session::get('filename');
            if(empty($FileName)) $FileName="";
        }
        $Info=db('article_temp')->where('TempArticleID',$TempArticleID)->where('member_id',$this->AgencyMemberID)->find();
        if(empty($Info)){
            $Data=array();
            $Data['TempArticleID']=$TempArticleID;
            $Data['member_id']=$this->AgencyMemberID;
            $Data['article_title']=$title;
            $Data['article_content']=$editorValue;
            $Data['article_remarks']=$beizhu;
			$Data['article_customer']=$article_customer;
            $Data['article_doc']=$FileName;
            $Data['article_time']=time();
            db('article_temp')->data($Data)->insert();
            //dump($Data);exit;
        }else{
            $title = $Info['article_title'];
            $beizhu = $Info['article_remarks'];
			$article_customer = $Info['article_customer'];
            $editorValue = $Info['article_content'];
            Session::set('filename',$Info['article_doc']);
        }
		$List= db('newsdynamics')
            ->where('NewsState',1)
			->where('NewsTypeID',1)
            ->order('NewsSort desc,NewsID Desc')
            ->limit(6)
			->select();
        $this->assign('list',$List);
        $this->assign('title',$title);
        $this->assign('beizhu',$beizhu);
		$this->assign('article_customer',$article_customer);
		$this->assign('starttime',$starttime);

        $this->assign('editorValue',$editorValue);
        $this->assign('TempArticleID',$TempArticleID);
        $this->assign('Money',$this->AgencyMemberInfo['MemberAgentBalanceCount']);
        return $this->fetch();
    }
    /**
     * 预览
     */
    public function look()
    {
        $id = input('id');
        if($id)
        {
            $Info = db('agencyorder')
                ->alias('A')
                ->where('AR.member_id|A.agency_id|A.agency_id1',$this->AgencyMemberID)
                ->where('AR.article_id',$id)
                ->join('article AR','A.article_id = AR.article_id')
                ->find();			
            $this->assign('title',$Info['article_title']);
            $this->assign('html',$Info['article_content']);
        }else{
            $this->assign('title',input('opentitle'));
            $this->assign('html',input('opencontent'));
        }
        return view();
    }
    /**
     * 上传文档
    */
    public function upload(){
        date_default_timezone_set("Asia/Shanghai");
        $FilePathInfo=$this->OneUpload('file');
        if(!empty($FilePathInfo)){
            
            $Info=$this->WordUpLoad($FilePathInfo);
            if(empty($Info)) return json(2);
            return json($Info);
        }
        return json(1);
    }
    /**
     * word中的图片解析
     */
    public function base64_image_content($base64_image_content,$path){
    //匹配出图片的格式
    if (preg_match('/^(data:\s*image\/(\w+);base64,)/', $base64_image_content, $result)){
        $type = $result[2];
        $new_file = date('Ymd',time())."/";
        if(!file_exists($path.$new_file)){
            //echo $path.$new_file;
            //检查是否有该文件夹，如果没有就创建，并给予最高权限
            mkdir($path.$new_file, 0777);
        }
        list($msec, $sec) = explode(' ', microtime());
        $msectime = (float)sprintf('%.0f', (floatval($msec) + floatval($sec)) * 1000);
        //echo  $base64_image_content;
        $new_file = $new_file.$msectime.rand(0,1000).".{$type}";
        $base64_string= explode(',', $base64_image_content); //截取data:image/png;base64, 这个逗号后的字符
        $base64_image_content= ($base64_string[1]);
        if (file_put_contents($path.$new_file, base64_decode(str_replace($result[1], '', $base64_image_content)))){
            return '/'.$new_file;
        }else{
            echo -1;
            return false;
        }
    }else{
        //echo 0;
        return false;
    }
}
   /**
     * word上传
     */
    public function WordUpLoad($file)//
    {
        Session::set('filename',$file);
        header('Content-Type:text/html; charset=utf-8');
        $file = PUBLIC_PATH.'uploads/word/'.$file;
        if(empty($file)) return false;
		$GetExtension=pathinfo($file,PATHINFO_EXTENSION );
        $html_file= pathinfo($file,PATHINFO_DIRNAME).'/'.pathinfo($file,PATHINFO_FILENAME).'.html';
		exec("/usr/bin/sudo /usr/bin/unoconv -f html " .$file." && chown www.www {$html_file}");
        //$html_file= pathinfo($file,PATHINFO_DIRNAME).'/'.explode('.',pathinfo($file,PATHINFO_BASENAME))[0].'.html';

        $myfile = fopen($html_file, "r") or die("Unable to open file!");
        Vendor('simplehtml/simple_html_dom');
        $html_dom = new simple_html_dom($html_file);
        $filter_tags=['p','font','span','a','img'];
        foreach ($filter_tags as $f => $tag) {
            foreach($html_dom->find($tag) as $e) {
                foreach ($e->getAllAttributes () as $key => $value) {
                    if($key!='src') $e->removeAttribute ($key);
                }
                if($tag=='img') $e->setAttribute ('width', 500 );
                else{
                        $e_tmp=$e;
                    if(trim($e->innertext)=='') $e->outertext = '';
                }
            }
        }
        $p = $html_dom->find('body', 0)->find('*', 0);
        $p->setAttribute('style', 'text-align:center');
        $head=$html_dom->find('head');
        $head[0]->outertext = '';
            foreach($html_dom->find('img') as $e) {
                $new_src=$this->base64_image_content($e->src,'../public'.DIRECTORY_SEPARATOR.'uploads'. DIRECTORY_SEPARATOR.'word'. DIRECTORY_SEPARATOR.'img'. DIRECTORY_SEPARATOR);
                if(!$new_src) continue;
                $e->setAttribute('src', 'http://www.zxal.cn/uploads/word/img'.$new_src);
                //$e->setAttribute('src', '/uploads/word/img'.$new_src);
                $e->parent->setAttribute('style', 'text-align:center');
         }
        $html= $html_dom;
		$html=str_replace('<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">','',$html);
		$pathimg="http://www.zxal.cn/uploads/word/".date("Ymd",time()).'/';
		$pregRule = "/<[img|IMG].*?src=[\'|\"](.*?(?:[\.jpg|\.jpeg|\.png|\.gif|\.bmp]))[\'|\"].*?[\/]?>/";
		$html = preg_replace($pregRule, '<img src="'.$pathimg.'${1}" style="max-width:100%">', $html);
		$html = preg_replace('|<h[\d]{1}[^>]+>(.*?)</h[\d]{1}>|i', '<p style="text-align: center;">$1</p>', $html);
       return [
            'title'=>strip_tags($p->innertext),
            'html'=>$html
       ];
    }
   /**
     * 提交订单
     */
    public function sborder()
    {
        if(!input('title')) return '文章标题不能为空';
        $TempArticleID =       input('TempArticleID');
        $TempArticleInfo=db('article_temp')->where('TempArticleID',$TempArticleID)->where('member_id',$this->AgencyMemberID)->find();
        $editorValue = $TempArticleInfo['article_content'];
        $beizhu =      $TempArticleInfo['article_remarks'];
        $title =       $TempArticleInfo['article_title'];
		$article_customer = $TempArticleInfo['article_customer'];
		$starttime =      input('starttime');
        $article_doc =       $TempArticleInfo['article_doc'];
        db('article_temp')->where('TempArticleID','')->delete();//删除空记录
        db('article_temp')->where('TempArticleID',$TempArticleID)->where('member_id',$this->AgencyMemberID)->delete();//删除临时ID记录
        $Model=new \app\member\model\Media();
        $idArr = explode(',',input('str'));
        $list = Db::name('media')
            ->where('MediaID','in',$idArr)
            ->select();
        if(!$list) return '请选择媒体';
        $AMoney = 0;
        $AMoney2 = 0;
        foreach ($list as $key=>$val)
        {
            $AMoney+= controller('common/Common')->price($this->AgencyMemberInfo['MemberID'],$val['MediaID']);
            if($this->AgencyMemberInfo['MemberRecommendID']) $AMoney2+= controller('common/Common')->price($this->AgencyMemberInfo['MemberRecommendID'],$val['MediaID']);
        }
        if($this->AgencyMemberInfo['MemberAgentBalanceCount'] < $AMoney) return '余额不足';
        
        $fuji = Db::name('member')->where('MemberID',$this->AgencyMemberInfo['MemberRecommendID'])->find();
        //dump($fuji);
        if($fuji) if($fuji['MemberAgentBalanceCount'] < $AMoney2) return '系统错误';
        //推送状态
        $push_state = Db::name('member')
            ->alias('M')
            ->where('MemberID',$this->AgencyMemberInfo['MemberRecommendID'])
            ->value('MemberTypeID');
        if(!$push_state) $push_state = 4;
        $data = [];
        $data['agency_member_id'] = $this->AgencySiteInfo['MemberID'];
        $data['member_id'] = $this->AgencyMemberID;
        $data['article_num'] = 'wz'.$this->ordernum();
        $data['article_title'] = $title;
        $data['article_content'] = $editorValue;
        $data['article_remarks'] = $beizhu;
		$data['article_customer'] = $article_customer;
        $data['article_time'] = time();
        $data['article_doc'] = Session::get('filename');
        $wzid = Db::name('article')->insertGetId($data);
        foreach ($list as $key=>$val)
        {
			if($val['UserType']==4){
				$unionstr='DK';
			}else{
				$unionstr='dd';
			}
			$ordernum = $unionstr.$this->ordernum();
            $Money = controller('common/Common')->price($this->AgencyMemberID,$val['MediaID']);
            $data = [];
            $data['order_number']  = $ordernum;
            $data['media_id']  = $val['MediaID'];
            $data['media_name']  = $val['MediaTitle'];
			$data['member_id']  = $val['MediaMemberID'];
            $data['media_money']  = $val['MediaWebPrice'];
            $data['article_id']  =$wzid;
            $data['push_state']  = $push_state;
            $data['order_time']  = time();
			if(empty($starttime) && intval($starttime)<=0){
				$data['order_state'] = '0';
			}else{
				$data['order_state'] = '5';
			}

			$data['media_type'] = '1';
			$data['starttime'] = $starttime;
            $data['order_money']  = $Money;
			$data['need_update'] = '0';
            $data['RegDomain']  =$this->AgencySiteInfo['Domain'];
            if($fuji){
                $data['order_money2'] = $Money;
                $data['agency_id'] = $this->AgencyMemberID;
            }else{
                $data['order_money1'] = $Money;
                $data['agency_id1'] = $this->AgencyMemberID;
            }
            $orderid = Db::name('agencyorder')->insertGetId($data);
			if(empty($starttime) && intval($starttime)<=0){
				if($val['UserType']==3){
					$this->error('请联系qq：1227187938 开通发送接口');
							exit;
				}elseif($val['UserType']==4){
					$this->error('请联系qq：1227187938 开通发送接口');
							exit;
				}
			}
            Db::name('member')->where('MemberID',$this->AgencyMemberID)->setDec('MemberAgentBalanceCount',$Money);
            $xj = Db::name('member')->where('MemberID',$this->AgencyMemberID)->value('MemberAgentBalanceCount');
            $data = [];
            $data['BalanceMemberID'] = $this->AgencyMemberID;
            $data['BalanceNumber'] = $ordernum;
            $data['BalanceType'] = 2;
            $data['BalanceCount'] = $Money;
            $data['BalanceCurrentCount'] = $xj;
            $data['BalanceTime'] = time();
            $data['BalanceGroup'] = '4';
            $data['BalanceState'] = '1';
            $data['BalanceTitle'] = '媒体发布';
            Db::name('balance')->insert($data);
            if($fuji){
                $Money = controller('common/Common')->price($fuji['MemberID'],$val['MediaID']);
                $data = [];
                $data['order_money1'] = $Money;
                $data['agency_id1'] = $fuji['MemberID'];
                Db::name('agencyorder')->where('agencyorder_id',$orderid)->update($data);
                Db::name('member')->where('MemberID',$fuji['MemberID'])->setDec('MemberAgentBalanceCount',$Money);
                $xj = Db::name('member')->where('MemberID',$fuji['MemberID'])->value('MemberAgentBalanceCount');
                $data = [];
                $data['BalanceMemberID'] = $fuji['MemberID'];
                $data['BalanceNumber'] = $ordernum;
                $data['BalanceType'] = 2;
                $data['BalanceCount'] = $Money;
                $data['BalanceCurrentCount'] = $xj;
                $data['BalanceTime'] = time();
                $data['BalanceGroup'] = '4';
                $data['BalanceState'] = 1;
                $data['BalanceTitle'] = '媒体发布';
                Db::name('balance')->insert($data);
            }
        }
        return 1;
    }
    public function ordernum()
    {
        $danhao = date('Ymd') . str_pad(mt_rand(1, 99999), 5, '0', STR_PAD_LEFT) ;
        return $danhao;
    }
    //单文件上传
    protected function OneUpload($FileName=''){
        if(empty($FileName)) return false;
        // 获取表单上传文件 例如上传了001.jpg
        $file = request()->file($FileName);
        if(empty($file)){ return false;}
        // 移动到框架应用根目录/public/uploads/ 目录下
        $FileSize=20*1024*1024;
        $FileSeat='uploads/word/';
        $FileExt='doc,docx,txt';
        $info = $file->validate(['size'=>$FileSize,'ext'=>$FileExt])->move(PUBLIC_PATH . $FileSeat);
        if($info){
            $getSaveName=$info->getSaveName();
            $getSaveName=str_replace('\\','/',$getSaveName);
            return $getSaveName;
        }else{
            return $info;
        }
    }
}