<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/10/31
 * Time: 20:37
 */
namespace app\agency_admin\controller;
use app\agency_admin\model\Invoice as InvoiceModel;
use think\Db;
class Invoice extends Common
{
	protected $AgencyMemberID='';
    protected $AgencyMemberName='';
    protected $AgencyMemberInfo=array();
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->AgencyMemberInfo=Db::name('member')->where('MemberID',$this->AgencyMemberID)->find();
        $this->assign('AgencyMemberInfo',$this->AgencyMemberInfo);
        $this->assign('AgencyMemberID',$this->AgencyMemberID);
        $this->assign('AgencyMemberName',$this->AgencyMemberName);
    }
    public function index()
    {
        $this->assign('InvoiceExpress',$this->GetCurrentWholeType(1));//快递名称
        $this->assign('InvoiceType',$this->GetCurrentWholeType(2));//发票类型
        $this->assign('InvoiceDetail',$this->GetCurrentWholeType(3));//发票明细
        return view();
    }
    //Ajax调用部分 Begin ----------------------------------
    public function getlist(){
        $UrlParam=input('get.');
        $this->assign('UrlParam',$UrlParam);
        $Where=array();
        $Where['InvoiceMemberID']=$this->AgencyMemberID;
        $Model=new InvoiceModel();
        $List=$Model->GetAgencyInvoiceList($UrlParam,$Where,20);
        $Back=array();
        $Back['code']='0';
        $Back['count']=$List->total();
        $Back['msg']='发票列表';
        $Back['data']=$List->items();
        return json($Back);
    }
    public function add()
    {
        if($this->request->isPost()){
            $data=input('post.');
//            echo '<pre>';
//            print_r($data);
            $data['InvoiceMemberID']=$this->AgencyMemberID;
            $data['InvoiceTime'] =time();
            Db::name('invoice')->insert($data);
            //echo Db::name('invoice')->getLastSql();
            $this->success('申请成功');
         }
        $this->assign('InvoiceExpress',$this->GetCurrentWholeType(1));//快递名称
        $this->assign('InvoiceType',$this->GetCurrentWholeType(2));//发票类型
        $this->assign('InvoiceDetail',$this->GetCurrentWholeType(3));//发票明细
        return view();
    }
    public function invoiceinfo()
    {
        $ID=input('id','','abs');
        $Info=db('invoice')->where('InvoiceID',$ID)->find();

		if(!$Info){
			$this->error('信息错误');
		}

        $Info['InvoiceTypeName']=db('wholetype')->where('TypeID',$Info['InvoiceType'])->value('TypeName');
        $InvoiceDetailName='';
        if($Info['InvoiceDetail']==999){
            $InvoiceDetailName='其他';
        }else{
            $InvoiceDetailName=db('wholetype')->where('TypeID',$Info['InvoiceDetail'])->value('TypeName');
        }
        $Info['InvoiceDetailName']=$InvoiceDetailName;
        $Info['InvoiceExpressName']=db('wholetype')->where('TypeID',$Info['InvoiceExpress'])->value('TypeName');
        $InvoiceStateName='';
        if($Info['InvoiceState']==0){
            $InvoiceStateName='申请中';
        }else if($Info['InvoiceState']==1){
            $InvoiceStateName='申请失败';
        }else if($Info['InvoiceState']==2){
            $InvoiceStateName='已寄出';
        }
        $Info['InvoiceStateName']=$InvoiceStateName;
        $this->assign('Info',$Info);
        return view();
    }
}