<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/5
 * Time: 11:21
 */
namespace app\agency_admin\controller;
use think\Db;
use think\Request;
use think\Loader;
class Media extends Common
{
    protected $AgencyMemberID='';
    protected $AgencyMemberName='';
    protected $AgencyMemberInfo=array();
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->AgencyMemberInfo=Db::name('member')->where('MemberID',$this->AgencyMemberID)->find();
        $this->assign('AgencyMemberInfo',$this->AgencyMemberInfo);
        $this->assign('AgencyMemberID',$this->AgencyMemberID);
        $this->assign('AgencyMemberName',$this->AgencyMemberName);
        $this->MemberID=$this->AgencyMemberID;
		$this->assign('MediaWebNameID',GetCurrentWholeType(18));//	频道类型
        $this->assign('MediaIndustryID',GetCurrentWholeType(35));//综合门户媒体
        $this->assign('MediaCityID',GetCityTypeList('0'));//覆盖区域
        $this->assign('MediaInLevelID',GetCurrentWholeType(110));//入口级别
        $this->assign('MediaUrlTypeID',GetCurrentWholeType(59));//链接类型
        $this->assign('MediaSpeedID',GetCurrentWholeType(66));//发稿速度
        $this->assign('MediaNewsSourceID',GetCurrentWholeType(73));//新闻源
        $this->assign('MediaCanSendID',GetCurrentWholeType(76));//周末可发
        $this->assign('MediaSpecialIndustryID',GetCurrentWholeType(79));//特别行业
        $this->assign('MediaSituationID',GetCurrentWholeType(85));//收录情况
        $this->assign('MediaComputerWeightID',GetCurrentWholeType(88));//电脑权重
        $this->assign('MediaMobileWeightID',GetCurrentWholeType(99));//移动权重
		$this->assign('MediaMobileWeightID',GetCurrentWholeType(99));//移动权重
		$this->assign('MediaPrice',MpriceNum());//媒体价格
    }
    public function index()
    {

        return view();
    }
    /**
     * 获得媒体列表
     */
    public function getlist()
    {
        $UrlParam=input('get.');
        $this->assign('UrlParam',$UrlParam);
        $Where=array();
        //$Where['agency_id']=$this->AgencyMemberID;
        $Model=new \app\member\model\Media();
        $List=$Model->GetMediaList($UrlParam,$Where,20,$this->AgencyMemberInfo,$this->AgencyMemberID,$this->AgencySiteInfo,$this->AgencyMemberInfo['MemberPriceType']-115);
        $Back=array();
        $Back['code']='0';
        $Back['count']=$List->total();
        $Back['msg']='媒体列表';
        $Back['data']=$List->items();
        return json($Back);
    }
     //导出
    public function exportexcel()
    {
        $UrlParam=input();
        $MemberInfo=db('member')->where('MemberID',$this->AgencyMemberID)->find();
        $name='媒体价格';
        $Where=array();
        $Where['agency_id']=$this->AgencyMemberInfo['MemberID'];
        $Model=new \app\member\model\Media();
        $Info=$Model->GetMediaListFull($UrlParam,[],$this->AgencyMemberID,$this->AgencyMemberID);
        if(!empty($Info)){
            if(count($Info)>1000){
                $this->alert('导出的数据不能超过1000条','back');
                exit;
            }
            if(!empty($UrlParam['jump']) && $UrlParam['jump']=='yes') return json('0');
            //获取标题
            $TitleInfo=GetExportTitle('memmerdia');
            excelExport($name,$TitleInfo,$Info);
        }else{
            $this->alert('导出的数据为空','back');
            exit;
        }
    }
    //收藏
    public function collect(){
        $ID=input('MediaID','','intval');
        $MemberID=$this->AgencyMemberID;
        if($MemberID<=0) $this->result('','1','请先登录，再加入收藏');
        $Where=array();
        $Where['CollectMemberID']=$MemberID;
        $Where['CollectGoodsID']=$ID;
        $Where['CollectAgencyDomainID']=$this->AgencySiteInfo['MemberID'];
        $count=Db::name('collect')->where($Where)->count();
        if($count>0) {
            //$this->result('','2','您已收藏');
            Db::name('collect')->where($Where)->delete();
            $this->result('','2','您已取消');
        }
        $Data=array();
        $Data['CollectMemberID']=$MemberID;
        $Data['CollectGoodsID']=$ID;
        $Data['CollectAgencyDomainID']=$this->AgencySiteInfo['MemberID'];
        $Data['CollectTime']=time();
        Db::name('collect')->insert($Data);
        $this->result('','0','收藏成功');
    }
}