<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/5
 * Time: 11:21
 */
namespace app\agency_admin\controller;
use app\member\model\Wemedia as WemediaModel;
use think\Db;
use think\Request;
use think\Loader;
class Wemedia extends Common
{
    protected $AgencyMemberID='';
    protected $AgencyMemberName='';
    protected $AgencyMemberInfo=array();
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->AgencyMemberInfo=Db::name('member')->where('MemberID',$this->AgencyMemberID)->find();
        $this->assign('AgencyMemberInfo',$this->AgencyMemberInfo);
        $this->assign('AgencyMemberID',$this->AgencyMemberID);
        $this->assign('AgencyMemberName',$this->AgencyMemberName);
        $this->MemberID=$this->AgencyMemberID;
		$this->assign('MediaWebNameID',GetCurrentWholeType(157));//	平台
        $this->assign('MediaIndustryID',GetCurrentWholeType(160));//行业类型
        $this->assign('MediaCityID',GetCityTypeList('0'));//覆盖区域
		$this->assign('fennumid',FanNum());//粉丝数
        $this->assign('MediaRedID',ReadNum());//阅读数
		$this->assign('pricenum',PriceNum());
		$this->assign('auth',AuthNum());
		$this->assign('can_video',Can_video());
		$this->assign('weekend_publish',Weekend_publish());

    }
    public function index()
    {
        return view('wemedia');
    }
    /**
     * 获得媒体列表
     */
    public function getlist()
    {
        $UrlParam=input('get.');
        $this->assign('UrlParam',$UrlParam);
        $Where=array();
        $Model=new WemediaModel;
        $List=$Model->GetMediaList($UrlParam,$Where,20,$this->AgencyMemberInfo,$this->AgencyMemberID,$this->AgencySiteInfo,$this->AgencyMemberInfo['MemberPriceType']-115);
		 
        $Back=array();
        $Back['code']='0';
        $Back['count']=$List->total();
        $Back['msg']='自媒体列表';
        $Back['data']=$List->items();
        return json($Back);
    }
     //导出
    public function exportexcel()
    {
        $UrlParam=input();
        $MemberInfo=db('member')->where('MemberID',$this->AgencyMemberID)->find();
 
		 
        $name='自媒体价格';
        $Where=array();
        $Where['agency_id']=$this->AgencyMemberInfo['MemberID'];
        $Model=new WemediaModel;
        $Info=$Model->GetWemediaListFull($UrlParam,[],$this->AgencyMemberID);
        if(!empty($Info)){
            if(count($Info)>1000){
                $this->alert('导出的数据不能超过1000条','back');
                exit;
            }
            if(!empty($UrlParam['jump']) && $UrlParam['jump']=='yes') return json('0');
            //获取标题
            $TitleInfo=GetExportTitle('wemerdia');
            excelExport($name,$TitleInfo,$Info);
        }else{
            $this->alert('导出的数据为空','back');
            exit;
        }
    }
    //收藏
    public function collect(){
        $ID=input('MediaID','','intval');
        $MemberID=$this->AgencyMemberID;
        if($MemberID<=0) $this->result('','1','请先登录，再加入收藏');
        $Where=array();
        $Where['CollectMemberID']=$MemberID;
        $Where['CollectGoodsID']=$ID;
        $Where['CollectAgencyDomainID']=$this->AgencySiteInfo['MemberID'];
		$Where['ctype']=2;
        $count=Db::name('collect')->where($Where)->count();
        if($count>0) {
            //$this->result('','2','您已收藏');
            Db::name('collect')->where($Where)->delete();
            $this->result('','2','您已取消');
        }
        $Data=array();
        $Data['CollectMemberID']=$MemberID;
        $Data['CollectGoodsID']=$ID;
        $Data['CollectAgencyDomainID']=$this->AgencySiteInfo['MemberID'];
        $Data['CollectTime']=time();
		$Data['ctype']=2;
        Db::name('collect')->insert($Data);
        $this->result('','0','收藏成功');
    }
}