<?php
/**
 * Created by PhpStorm.
 * User: Memberistrator
 * Date: 2018/1/4
 * Time: 9:49
 */
namespace app\admin\controller;
use app\admin\model\Alipay as AliPayModel;
use think\Db;
class Alipay extends Common
{
    private $PageCount=10;
    private $MenuName='支付宝';//栏目名称
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('MenuName',$this->MenuName);
    }
    public function adminpay()
    {
        if($_POST)
        {
            $data = [];
            $data['AliPayAPPID'] = input('AliPayAPPID');
            $data['AliPayPublicKey'] = input('AliPayPublicKey');
            $data['AliPayPrivateKey'] = input('AliPayPrivateKey');
            $data['AliPayState'] = input('AliPayState');
            Db::name('alipay')->where('AliPayMemberID',0)->update($data);
        }
        $Info = Db::name('alipay')->where('AliPayMemberID',0)->find();
        $this->assign('Info',$Info);
        return $this->fetch();
    }
  public function index()
    {
        $UrlParam=input('get.');
        $Model=new AliPayModel();
        $List=$Model->GetList($UrlParam,$this->PageCount);
        $this->assign('List',$List);
        $this->assign('UrlParam',$UrlParam);
        return $this->fetch();
    }
    public function add(){
        if($this->request->isPost())
        {
            $Post=input('post.');
            $this->AddSave($Post);
        }else{
            return $this->fetch();
        }
    }
    //保存添加数据
    private function AddSave($Post)
    {
        $MemberModel=new \app\admin\model\Member();
        $Info=$MemberModel->field('MemberID')->where('MemberName',$Post['AliPayMemberName'])->find();
        if(empty($Info)) $this->alert('您所输入的用户名有误','back');
        $info2 = Db::name('alipay')->where('AliPayMemberID',$Info['MemberID'])->find();
        if($info2) $this->alert('该会员已存在账户','back');
        unset($Post['AliPayMemberName']);
        $file = request()->file('image');
        if($file){
            $info = $file->move(ROOT_PATH . 'uploads' . DS . 'erwm');
            if($info){
                $Post['AliPayPicture'] = str_replace('\\','/',$info->getSaveName());
            }else{
                $this->alert($file->getError(),'back');
            }
        }
        $file = request()->file('image2');
        if($file){
            $info = $file->move(ROOT_PATH . 'uploads' . DS . 'erwm');
            if($info){
                $Post['AliPayWXPicture'] = str_replace('\\','/',$info->getSaveName());
            }else{
                $this->alert($file->getError(),'back');
            }
        }
        $Post['AliPayType']=$Post['AliPayType'];
        $Post['AliPayMemberID']=$Info['MemberID'];
        $Model=new AliPayModel();
        $Model->save($Post);
        $InsertID=$Model->getLastInsID();
        AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'已添加成功','LogOperateContent'=>'ID:'.$InsertID]);
        $this->alert('此'.$this->MenuName.'已添加成功','back');
        exit;
    }
    public function edit()
    {
        if($this->request->isPost())
        {
            $Post=input('post.');
            $this->EditSave($Post);
        }else{
            $ID=input('id','','abs');
            $Model=new AliPayModel();
            $Info=$Model->where('AliPayID',$ID)->find();
            $Info['MemberName']=db('Member')->where('MemberID',$Info['AliPayMemberID'])->value('MemberName');
            $this->assign('Info',$Info);
            return $this->fetch();
        }
    }
    public function upimage(){
        // 获取表单上传文件 例如上传了001.jpg
        $file = request()->file('image');
        // 移动到框架应用根目录/public/uploads/ 目录下
        if($file){
            $info = $file->move(ROOT_PATH . 'uploads' . DS . 'excel');
            if($info){
                $info2 = Db::name('alipay')->where('AliPayMemberID',$this->AgencyMemberID)->find();
                $data = [];
                $data['AliPayStatet'] = input('state');
                $data['AliPayPicture'] = str_replace('\\','/',$info->getSaveName());
                if($info2)
                {
                    @unlink('public/uploads/'.$info2['AliPayPicture']);
                    Db::name('alipay')->where('AliPayMemberID',$this->AgencyMemberID)->update($data);
                }else{
                    $data['AliPayTime'] = time();
                    $data['AliPayMemberID'] = $this->AgencyMemberID;
                    Db::name('alipay')->insert($data);
                }
                $this->success('更新成功', 'pay');
            }else{
                echo $file->getError();
            }
        }
    }
    public function EditSave($Post){
        $AliPayID=$Post['AliPayID'];
        $Where=array();
        $Where['AliPayID']=$AliPayID;
        $file = request()->file('image');
        if($file){
            $info = $file->move(ROOT_PATH . 'uploads' . DS . 'erwm');
            if($info){
                $info2 = Db::name('alipay')->where('AliPayID',$AliPayID)->find();
                @unlink('uploads/erwm/'.$info2['AliPayPicture']);
                $Post['AliPayPicture'] = str_replace('\\','/',$info->getSaveName());
            }else{
                $this->alert($file->getError(),'back');
            }
        }
        $file2 = request()->file('image2');
        if($file2){
            $file2 = $file2->move(ROOT_PATH . 'uploads' . DS . 'erwm');
            if($file2){
                $info3 = Db::name('alipay')->where('AliPayID',$AliPayID)->find();
                @unlink('uploads/erwm/'.$info3['AliPayWXPicture']);
                $Post['AliPayWXPicture'] = str_replace('\\','/',$file2->getSaveName());
            }else{
                $this->alert($file->getError(),'back');
            }
        }
        $Post['AliPayType']=$Post['AliPayType'];
        $Model=new AliPayModel();
        if(!empty($Post['AliPayReplyTime']))$Post['AliPayReplyTime']=strtotime($Post['AliPayReplyTime']);
        $Model->save($Post,$Where);
        AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'已修改成功','LogOperateContent'=>'ID:'.$AliPayID]);
        $this->alert('此'.$this->MenuName.'已修改成功','back');
        exit;
    }
    //删除数据
    public function del()
    {
        if($this->request->isPost()){
            $this->delmore();
        }elseif($this->request->isGet()) {
            $ID = input('param.id');
            if (!empty($ID)) {
                $Model = new AliPayModel();
                $Model->where('AliPayID', $ID)->delete();
            }
            AdminLogDetail(['LogOperateTitle' => $this->MenuName . '记录删除成功', 'LogOperateContent' => 'ID:' . $ID]);
            //$this->success('此记录已删除成功');
            $this->alert('此记录已删除成功','back');
            exit;
        }
    }
    //批量删除记录
    private function delmore()
    {
        $DelID=input('post.Del/a');
        //dump($DelID);
        if(!empty($DelID))
        {
            $DelIDStr=implode(',',$DelID);
            $Model=new AliPayModel();
            $Model->where('AliPayID','in',$DelIDStr)->delete();
            AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'批量删除成功','LogOperateContent'=>'ID:'.$DelIDStr]);
        }
        //$this->success('此记录批量删除成功');
        $this->alert('此记录批量删除成功','back');
        exit;
    }
}