<?php
/**
 * Created by PhpStorm.
 * User: Memberistrator
 * Date: 2018/1/4
 * Time: 9:49
 */
namespace app\admin\controller;
use \app\admin\model\Article as ArticleModel;
use think\Db;
class Article extends Common
{
    private $PageCount=10;
    private $MenuName='软文';//栏目名称
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('MenuName',$this->MenuName);
        $this->assign('config',db('config')->where('MemberID','eq',-1)->find());
    }
    public function push_hezi(){
        $orderid=input('post.orderid');
		$order=db('agencyorder')->where('agencyorder_id','eq',$orderid)->find();
		$media=db('media')->where('MediaId','eq',$order['media_id'])->find();
		if($media['UserType'] ==4){
			echo controller('common/Daka')->push($orderid);
		}else{
			echo controller('common/Hezi')->push($orderid);
		}
    }
    public function query_hezi(){
        set_time_limit(0);
        controller('common/Hezi')->autoquery();
    }
    public function index(){
        $UrlParam=input('get.');
        $UrlParam['order_state'] = isset($UrlParam['order_state']) ? $UrlParam['order_state'] : '';
        $this->assign('UrlParam',$UrlParam);
        $StartDate=empty($UrlParam['startdate'])?'':$UrlParam['startdate'];
        $EndDate=empty($UrlParam['enddate'])?'':$UrlParam['enddate'];
        $where = [];
        if(!empty($UrlParam['keyword'])) $where['A.article_num|A.article_title'] = ['like','%'.$UrlParam['keyword'].'%'];
        if(!empty($UrlParam['order_number'])) $where['AO.order_number'] = ['like','%'.$UrlParam['order_number'].'%'];
		if(!empty($UrlParam['mphone'])) $where['M.MemberName'] = ['like','%'.trim($UrlParam['mphone']).'%'];
        
        if(isset($UrlParam['order_state']) && $UrlParam['order_state']>='0')$where['AO.order_state']=$UrlParam['order_state'];//状态
        if(!empty($StartDate) || !empty($EndDate)){
            if(!empty($StartDate) && !empty($EndDate)){
                $StartDate=strtotime($StartDate);
                $EndDate=strtotime($EndDate);
                $begin_time=min($StartDate,$EndDate);
                $end_time=max($StartDate,$EndDate);$end_time+=86399;
                $where['A.article_time']=['between',[$begin_time,$end_time]];
            }else if(!empty($StartDate) && empty($EndDate)){
                $StartDate=strtotime($StartDate.' 00:00:00');
                $where['A.article_time']=['>=',$StartDate];
            }else if(empty($StartDate) && !empty($EndDate)){
                $EndDate=strtotime($EndDate.' 23:59:59');
                $where['A.article_time']=['<=',$EndDate];
            }
        }
        if(isset($UrlParam['order_state']) && $UrlParam['order_state']>='0'){
            $this->assign('order_state',$UrlParam['order_state']);
        }else{
            $this->assign('order_state','');
        }
 		$where['AO.media_type']=1;
		$UrlParam['changedc'] = isset($UrlParam['changedc']) ? $UrlParam['changedc'] : '';
        if($UrlParam['changedc']==1){
			$where['C.state']=['neq',2];
            $list = Db::name('article')
            ->alias('A')
            ->field('A.*,M.MemberName,M.MemberRecommendPath,W.TypeName as hyjb,W2.TypeName as dljb,M.GroupID,AO.media_type')
            ->join('member M', 'M.MemberID=A.member_id', 'left')
            ->join('wholetype W', 'W.TypeID=M.MemberPriceType', 'left')
            ->join('membertype W2', 'W2.TypeID=M.MemberTypeID', 'left')
			->join('agencyorder AO', 'AO.article_id=A.article_id', 'left')
			->join('changedoc C', 'C.articleid=A.article_id', 'left')
            ->where($where)
            ->group('A.article_id')
            ->order('C.addtime desc')
            ->paginate(10,false,['query'  => $UrlParam]);
        }else{
            $list = Db::name('article')
            ->alias('A')
            ->field('A.*,M.MemberName,M.MemberRecommendPath,W.TypeName as hyjb,W2.TypeName as dljb,M.GroupID,AO.media_type')
            ->join('member M', 'M.MemberID=A.member_id', 'left')
            ->join('wholetype W', 'W.TypeID=M.MemberPriceType', 'left')
            ->join('membertype W2', 'W2.TypeID=M.MemberTypeID', 'left')
            ->join('agencyorder AO', 'AO.article_id=A.article_id', 'left')
            ->where($where)
            ->group('A.article_id')
            ->order('A.article_time desc')
            ->paginate(20,false,['query'  => $UrlParam]);
        }
        
       // echo db()->getLastSql();
        $str = '';
        $autopush=db('config')->where('MemberID','eq',-1)->find()['autopush'];
        foreach ($list as $key=>$val)
        {
            $name = $val['GroupID'] == 1?$val['hyjb']:$val['dljb'];
            $down_state = $val['down_state']==1 ? 'checked' : '';
            $DownFile=empty($val['article_doc'])?'':'<a href="'.url('filedown',['article_id'=>$val['article_id']]).'">文件下载</a>';
            $MemberRecommendPath_a=explode(',', $val['MemberRecommendPath']);
            $full_name='';
            foreach ($MemberRecommendPath_a as $key => $value) {
                $rs=Db::name('member')->where('MemberID','eq',$value)->find();
                if($full_name){
                    if($key==1){
                        $full_name=$full_name.'【'.$rs['MemberName'];
                    }else{
                        $full_name=$full_name.'-'.$rs['MemberName'];
                    }
                    
                }else{

                    $full_name='<b>'.$rs['MemberName'].'</b>';
                }                
            }
            if($val['MemberRecommendPath']==0) $full_name='<b>'.$val['MemberName'].'</b>';//主站平台
            if(sizeof($MemberRecommendPath_a)>1)   $full_name=$full_name.'】';

            $str.='<table class="layui-table">
            <thead>
            <tr>
                <th width="40" class="listtitle" rowspan="2">
                    <input type="checkbox" name="Del[]" lay-skin="primary" lay-filter="ItemBox" value="'.$val['article_id'].'" />
                </th>
                <th class="listtitle" colspan="8" style="text-align:left">'.$val['article_num'].'：<a  href="javascript:OpenWinSeeContent(\'' . url("see", ["id" => $val['article_id']]) . '\');">' . $val['article_title'] . '</a> <b style="color:red">备注：'. $val['article_remarks'].'</b>'			
			.'</th>
                <th class="" colspan="2" style="text-align:center">'.$full_name.'('.$name.')</th>
                <th class="listtitle" colspan="2">'.date("m-d H:i",$val['article_time']).' <a href="'.url('editcontent',['article_id'=>$val['article_id']]).'"> [修改] </a></th>
                <th class="listtitle" colspan="1">'.$DownFile.'</th>
            </tr>
            <tr>
                <th width="200" class="listtitle" colspan="2">标题</th>
                <th class="listtitle">媒体</th>
                <th class="listtitle">平台价</th>
                <th class="listtitle">游客价</th>
                <th class="listtitle">大侠价</th>
                <th class="listtitle">掌门价</th>
                <th class="listtitle">盟主价</th>
                <th class="listtitle">成交价</th>
                <th class="listtitle">回链</th>
                <th width="70" class="listtitle">审核进度</th><th class="listtitle">推送状态</th>
                <th width="100" class="listtitle">操作</th>
            </tr>
            </thead>  <tbody>';
            $where=array();
            $where['article_id']=$val['article_id'];
            if(isset($UrlParam['order_state']) && $UrlParam['order_state']>='0')$where['order_state']=$UrlParam['order_state'];//状态
            $count = Db::name('agencyorder')->where($where)->count();
            $where=array();
            $where['A.article_id']=$val['article_id'];
			$where['A.media_type']=1;
            if(isset($UrlParam['order_state']) && $UrlParam['order_state']>='0')$where['A.order_state']=$UrlParam['order_state'];//状态
            $orderlist = Db::name('agencyorder')
                ->alias('A')
                ->field('A.*,M.MediaTitle,M.MediaWebPrice,M.MediaMemberPrice1,M.MediaMemberPrice2,M.MediaMemberPrice3,M.MediaMemberPrice4,M.MediaMemberPrice5,M.UserType,M.MediaMemberID')
                ->join('media M', 'M.MediaID=A.media_id', 'left')
                ->where($where)
                ->select();
            $typearr = ['待审核','发布中','已发布','已拒稿','已取消','定时发布'];
            $vk = 0;
            foreach ($orderlist as $k=>$v){
                    $str .= ' <tr>';
                    if ($vk == 0) {
                        $vk++;
                    }
                    if($val['agency_member_id']=='-1'){
                        $cjj = $v['order_money'];
                    }else{
                        $cjj = $v['order_money1'];
                    }
                    $SeeStr='';
                    $SeeStr=$v['fabu_site'];
                    $SeeStr.=empty($v['fabu_content'])?'':'<br>'.$v['fabu_content'];
                    $SeeStr.=empty($v['release_time'])?'':'<br>'.date('Y-m-d H:i:s',$v['release_time']);
                    $StateStr='';
					/*
                    if(!empty($v['order_state']) && $v['order_state']==1) {
                        $StateStr = '<span style="color:red;">' . $typearr[$v['order_state']] . '</span>';
                    }elseif(!empty($v['order_state']) && $v['order_state']==4){
                        $StateStr = '<span style="color:green;">' . $typearr[$v['order_state']] . '</span>';
                    }else{
                        $StateStr=''.$typearr[$v['order_state']].'';
                    }*/
					if ($v['order_state']==0)
						{
							$StateStr='<span style="color:red">待审核</span>';
						}elseif($v['order_state']==1)
						{
							$StateStr='<span style="color:red">发布中</span>';
						}elseif($v['order_state']==2)
						{
							$StateStr='<span style="color:green">已发布</span>';
						}elseif($v['order_state']==3)
						{
							$StateStr='已退稿';
						}elseif($v['order_state']==4)
						{
							$StateStr='已取消';
						}elseif($v['order_state']==5)
						{
							$StateStr='定时发送';
						}

                    $BackLink=$v['order_state']==2?' style="color:red;" ':'';
                    $str .=  '<td align="center" colspan="3">'. $v['order_number'].'</td>';
							if($v['UserType']!=2){
								$str .=  '<td align="center">' . $v['MediaTitle'] . '</td>';
							}else{
								 $MemberQQ=Db::name('member')->where('MemberID','eq',$v['MediaMemberID'])->value('MemberQQ');
								  $MemberName=Db::name('member')->where('MemberID','eq',$v['MediaMemberID'])->value('MemberName');
 								 $str .=  '<td align="center">' . $v['MediaTitle'] . '<a href="http://wpa.qq.com/msgrd?v=3&amp;uin='.$MemberQQ.'&amp;site=qq&amp;menu=yes" target="_blank" class="qq_contact"></a><b style="color:green">['.$MemberName.']</b></td>';
							}
							 $str .=  '<td align="center">' . $v['MediaWebPrice'] . '</td>
                            <td align="center">' . $v['MediaMemberPrice1'] . '</td>
                            <td align="center">' . $v['MediaMemberPrice2'] . '</td>
                            <td align="center">' . $v['MediaMemberPrice3'] . '</td>
                            <td align="center">' . $v['MediaMemberPrice4'] . '</td>
                            <td align="center">' . $cjj . '</td>
                            <td align="center"><a href="javascript:OpenWinSeeLink(\'' .$SeeStr. '\');"  '.$BackLink.'>点击查看</a></td>
                            <td align="center">' . $StateStr . '</td>';

							if($v['UserType']!=2){

								 $str .= '<td align="center">'. ($v['push_hezi']==0?'<b style="color:red">未推送</b>':'已推送').'</td>';

							}else{
								 $str .='<td align="center">'. ($v['UserType']==2?'<b style="color:green">[自营]</b>':'').'</td>';
							 }
							 $str .='<td align="center"><div">';
							 if($v['UserType']!=2){
								 if($v['push_hezi']==0 && $v['order_state']==0)
								$str .='<a style="cursor:pointer" class="push_order" data-id="'.$v['agencyorder_id'] . '">推送</a> ';
							 }
							 $str .='<a target="_blank" href="' .'/index/look/id/'.$val['article_id'].'/snid/'.$v['agencyorder_id'].'">预览</a>
                                    <a class="layui-btn layui-btn-mini" href="javascript:OpenWinSeeContent(\'' . url("edit", ["id" => $v['agencyorder_id']]) . '\');">编辑</a>
                                </div>
                            </td>
                        </tr>';
            }
            $str.='</tbody></table> ';
        }
        $this->assign('html',$str);
		$changecount = Db::name('changedoc')->where("state",'neq',2)->count();
		$this->assign('changecount',$changecount);
        $this->assign('list',$list);
        return $this->fetch();
    }
    public function add(){
        if($this->request->isPost()){
            $Post=input('post.');
        }else{
            return $this->fetch();
        }
    }
    public function edit(){
        $ID=input('id','','abs');
        if(request()->isPost())
        {
            $order_state = input('order_state');
            $fabu_site = input('fabu_site');
            $fabu_content = input('fabu_content');
            $Contrller=controller('common/Common');
            if($order_state==4) controller('common/Hezi')->cancel($ID);
            $Contrller->Refund($ID,$order_state,$fabu_site,$fabu_content);
            $this->success('操作成功！');
        }
        $info = Db::name('agencyorder')
            ->alias('AO')
            ->field('AO.*,A.*,M.MediaTitle,A1.MemberName as Mem1,A2.MemberName as Mem2,A3.MemberName as Mem3,A3.GroupID,MT.TypeName as dljb,WT.TypeName as hyjb')
            ->where('AO.agencyorder_id',$ID)
            ->join('article A','A.article_id=AO.article_id','left')//文章
            ->join('media M', 'M.MediaID=AO.media_id', 'left')//媒体
            ->join('member A1', 'A1.MemberID=AO.agency_id1', 'left')//一级代理
            ->join('member A2', 'A2.MemberID=AO.agency_id', 'left')//二级代理
            ->join('member A3', 'A3.MemberID=A.member_id', 'left')//发布会员
            ->join('membertype MT', 'MT.TypeID=A3.MemberTypeID', 'left')
            ->join('wholetype WT', 'WT.TypeID=A3.MemberPriceType', 'left')
            ->find();
        $info['mlx'] = $info['GroupID'] == 1?$info['hyjb']:$info['dljb'];
        $this->assign('Info',$info);
        return $this->fetch();
    }
    public function see(){
        $ID=input('id','','abs');
        $info = Db::name('article')
            ->where('article_id',$ID)
            ->find();
        $this->assign('Info',$info);
        return $this->fetch();
    }
    public function filedown(){
        $article_id=input('article_id');
        $info = db('article')->where("article_id",$article_id)->find();
        if(empty($info)) return false;
        $file_path=PUBLIC_PATH.'uploads/word/'.$info['article_doc'];
        $Extension=pathinfo($file_path,PATHINFO_EXTENSION);
        $file_path=str_replace('\\','/',$file_path);
        $file_name=$info['article_title'].'.'.$Extension;
        ///www/wwwroot/rw.hnzhuofeng.cn/uploads/20181112
        ///www/wwwroot/rw.hnzhuofeng.cn/uploads/20181112/c0c930c5e14c5f80109de00ea2d8ad86.docx
        //echo $file_path;exit;
        FileDown($file_path,$file_name);
    }
    //删除数据
    public function del()
    {
        if($this->request->isPost())
        {
            $this->delmore();
        }
    }
    //批量删除记录
    private function delmore()
    {
        $DelID=input('post.Del/a');
        //dump($DelID);
        if(!empty($DelID))
        {
            $DelIDStr=implode(',',$DelID);
            //$this->DelOneOldPic($DelIDStr,'article','article_id','article_doc');
            Db::name('article')->where('article_id','in',$DelIDStr)->delete();
            Db::name('agencyorder')->where('article_id','in',$DelIDStr)->delete();
            AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'批量删除成功','LogOperateContent'=>'ID:'.$DelIDStr]);
        }
        //$this->success('此记录批量删除成功');
        $this->alert('此记录批量删除成功','back');
        exit;
    }
	public function editcontent(){
        $ID=input('article_id','','abs');
        $info = Db::name('article')
            ->where('article_id',$ID)
            ->find();
        $this->assign('Info',$info);
        return $this->fetch();
    }
	public function editsave(){
		$data=array();
		if($this->request->isPost())
        {
			$ID=input('id','','abs');
			$data['article_title']=input('article_title');
			$data['article_content']=input('editorValue');
			$data['article_remarks']=input('beizhu');

			$result=Db::name('article')->where('article_id',$ID)->update($data);
			if($result){
				$this->alert('修改成功','jump','index');
				exit;
			}
		}
	}
}
