<?php
/**
 * Created by PhpStorm.
 * User: Memberistrator
 * Date: 2018/1/4
 * Time: 9:49
 */
namespace app\admin\controller;
use \app\admin\model\Article as ArticleModel;
use think\Db;
class Exchangedraw extends Common
{
    private $PageCount=10;
    private $MenuName='抽奖活动';//栏目名称
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('MenuName',$this->MenuName);
        $this->assign('config',db('config')->where('MemberID','eq',-1)->find());
    }
	//奖项类型
    public function index(){
		$act =Db::name('draw_act')->find();
		$this->assign( 'act', $act );
		$aid = input('aid');
		if($aid > 0){
			if($this->request->isPost()){
				$Where=array();
				$Where['aid']=$aid;
				Db::name('draw_act')->save($Post,$Where);
			}else{
				return $this->fetch('act_show');
			}
		}
		return $this->fetch('act_list');
    }
	//查看奖项设置
	 public function listall(){
		$aid = intval(input('aid'));
		$actList = Db::name('draw_actlist')->where("aid",'eq',$aid)->order("lid asc")->select();
		$this->assign( 'actList', $actList );
		return $this->fetch( 'act_listall' );
	 }
	 //添加修改奖项
	 public function add(){
			$lid = input('lid');
			$data['title'] = input('title');
			$data['randnum'] = input('randnum');
			$data['num'] = input('num');
			$data['aid'] = input('aid');
			$actList=array();
			$countnum=Db::name('draw_actlist')->sum('randnum');

			if($lid > 0){
				$now_num=Db::name('draw_actlist')->where('lid','eq',$lid)->find();

				if($now_num['randnum']>$data['randnum']){
				
					$countnum=$countnum-($now_num['randnum']-$data['randnum']);
				}else{

					$countnum=$countnum+($data['randnum']-$now_num['randnum']);

				}
			}else{
				if($countnum+$data['randnum']>100){
					$this->error("百分比不得大于100%",url('/exchangedraw/listall/aid/3'));
				}
			}
			if($lid > 0){
				$actList=Db::name('draw_actlist')->where('lid','eq',$lid)->find();
				$this->assign( 'actList', $actList );
				if($this->request->isPost()){
					$result=Db::name('draw_actlist')->where('lid','eq',$lid)->update($data);
					if($result){
						$this->success("更新成功",url('/exchangedraw/listall/aid/3'));
					}else{
						$this->error("更新失败",url('/exchangedraw/listall/aid/3'));
					}
				}
			}else{
				if($this->request->isPost()){
					$result=Db::name('draw_actlist')->insert($data);
					if($result){
						$this->success("添加成功",url('/exchangedraw/listall/aid/3'));
					}else{
						$this->error("添加失败",url('/exchangedraw/listall/aid/3'));
					}
				}
			}
			$this->assign( 'actList', $actList );

		 return $this->fetch( 'act_add' );
	 }

	//会员中奖记录
    public function orderlist(){

			$UrlParam=input('get.');
			$this->assign('UrlParam',$UrlParam);
			$Keyword=input('keyword','');
			$List=Db::name('draw_actlog')
				  ->alias('l')
				  ->Join('member m','l.uid = m.MemberID')
				  ->order('l.lid Desc')
				  ->paginate(20,false,['query'=>['MemberName'=>$Keyword],]);
			  
			$this->assign( 'actList', $List );

			return $this->fetch();
	}
    //批量删除奖项记录
    public function del()
    {
        $DelID=input('post.Del/a');
        if(!empty($DelID))
        {
            $DelIDStr=implode(',',$DelID);
            Db::name('draw_actlist')->where('lid','in',$DelIDStr)->delete();
            AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'批量删除成功','LogOperateContent'=>'ID:'.$DelIDStr]);
        }
        $this->success('此记录批量删除成功');
        exit;
    }
}