<?php
/**
 * Created by PhpStorm.
 * User: Memberistrator
 * Date: 2018/1/4
 * Time: 9:49
 */
namespace app\admin\controller;
use app\admin\model\Message as MessageModel;
class Feedback extends Common
{
    private $PageCount=10;
    private $MenuName='问题反馈';//栏目名称
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('MenuName',$this->MenuName);
    }
    public function index()
    {
        $UrlParam=input('get.');
        $Model=new MessageModel();
        $List=$Model->GetList($UrlParam,$this->PageCount);
        $this->assign('List',$List);
        $this->assign('UrlParam',$UrlParam);
        return $this->fetch();
    }
    public function edit()
    {
        if($this->request->isPost())
        {
            $Post=input('post.');
            $this->EditSave($Post);
        }else{
            $ID=input('id','','abs');
            $Model=new MessageModel();
            $Info=$Model->where('MessageID',$ID)->find();
            $this->assign('Info',$Info);
            return $this->fetch();
        }
    }
    public function EditSave($Post){
        $MessageID=$Post['MessageID'];
        $Where=array();
        $Where['MessageID']=$MessageID;
        $Model=new MessageModel();
        if(!empty($Post['MessageReplyTime']))$Post['MessageReplyTime']=strtotime($Post['MessageReplyTime']);
        $Model->save($Post,$Where);
        AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'已修改成功','LogOperateContent'=>'ID:'.$MessageID]);
        $this->success('此'.$this->MenuName.'已修改成功');
        //$this->alert('此'.$this->MenuName.'已修改成功','back');
        exit;
    }
    //删除数据
    public function del()
    {
        if($this->request->isPost()){
            $this->delmore();
        }elseif($this->request->isGet()) {
            $ID = input('param.id');
            if (!empty($ID)) {
                $Model = new MessageModel();
                $Model->where('MessageID', $ID)->delete();
            }
            AdminLogDetail(['LogOperateTitle' => $this->MenuName . '记录删除成功', 'LogOperateContent' => 'ID:' . $ID]);
            //$this->success('此记录已删除成功');
            $this->alert('此记录已删除成功','back');
            exit;
        }
    }
    //批量删除记录
    private function delmore()
    {
        $DelID=input('post.Del/a');
        //dump($DelID);
        if(!empty($DelID))
        {
            $DelIDStr=implode(',',$DelID);
            $Model=new MessageModel();
            $Model->where('MessageID','in',$DelIDStr)->delete();
            AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'批量删除成功','LogOperateContent'=>'ID:'.$DelIDStr]);
        }
        //$this->success('此记录批量删除成功');
        $this->alert('此记录批量删除成功','back');
        exit;
    }
}