<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/7/24
 * Time: 11:23
 */
namespace app\admin\controller;
use think\Db;
use app\admin\model\Help as HelpModel;
class Help extends Common
{
    private $MenuName = '帮助中心';
    private $PageCount=15;
    //公共的方法调用
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('FileSeat','/'.config('config.FileSeat').'/');
        $this->assign('MenuName', $this->MenuName);
    }
    //帮助中心列表
    public function index()
    {
        $UrlParam=input('get.');
        $this->assign('UrlParam',$UrlParam);
        $Keyword=input('keyword','');
        $Model=new HelpModel();
        $List = $Model->GetList($this->PageCount,$Keyword);
        $this->assign('List', $List);
        return $this->fetch();
    }
    //帮助中心添加
    public function add()
    {
        if($this->request->isPost())
        {
            $Post=input('post.');
            $this->AddSave($Post);
        }else{
            //调取商品级联菜单
            $HelpTypeListOne=$this->CallHelpMenu('0');
            //dump($HelpTypeListOne);
            $this->assign('HelpTypeListOne',$HelpTypeListOne);
            return $this->fetch();
        }
    }
    //保存添加数据
    private function AddSave($Post)
    {
        $Model=new HelpModel();
        //图片上传
        $PicPath=$this->OneUpload('HelpPicPath');
        if(!empty($PicPath)){
            $Post['HelpPicPath']=$PicPath;
        }
        $Model->save($Post);
        $InsertID=$Model->getLastInsID();
        AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'已添加成功','LogOperateContent'=>'ID:'.$InsertID]);
//        $this->success('此'.$this->MenuName.'已添加成功');
        $this->alert('此'.$this->MenuName.'已添加成功','back');
        exit;
    }
    //数据修改
    public function edit()
    {
        if($this->request->isPost())
        {
            $Post=input('post.');
            $this->EditSave($Post);
        }else{
            $ID=input('param.id','','abs');
            $Model=new HelpModel();
            $Info=$Model->get($ID);
            $this->assign('Info',$Info);
            //商品分类获取
            $HelpTypePathArr=['0','0','0'];
            if(!empty($Info['HelpTypePath']))
            {
                $HelpTypePathArr=explode(',',$Info['HelpTypePath']);
            }
            $this->assign('HelpTypePathArr',$HelpTypePathArr);
            //调取商品级联菜单  一级分类
            $HelpTypeListOne=$this->CallHelpMenu('0');
            //dump($HelpTypeListOne);
            $this->assign('HelpTypeListOne',$HelpTypeListOne);
            //调取商品级联菜单  二级分类
            $HelpTypeListTwo=[];
            if(!empty($HelpTypePathArr[0])){
                $HelpTypeListTwo=$this->CallHelpMenu($HelpTypePathArr[0]);
            }
            //dump($HelpTypeListOne);
            $this->assign('HelpTypeListTwo',$HelpTypeListTwo);
            //调取商品级联菜单  三级分类
            $HelpTypeListThree=[];
            if(!empty($HelpTypePathArr[1])) {
                $HelpTypeListThree = $this->CallHelpMenu($HelpTypePathArr[1]);
            }
            //dump($HelpTypeListOne);
            $this->assign('HelpTypeListThree',$HelpTypeListThree);
            return $this->fetch();
        }
    }
    //保存修改数据
    private function EditSave($Post)
    {
        $HelpID=$Post['HelpID'];
        //图片上传
        $PicPath=$this->OneUpload('HelpPicPath');
        if(!empty($PicPath)){
            $this->DelOneOldPic($HelpID,'help','HelpID','HelpPicPath');//先删除
            $Post['HelpPicPath']=$PicPath;
        }
        $Where=[];
        $Where['HelpID']=$HelpID;
        $Model=new HelpModel();
        $Model->save($Post,$Where);
        AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'已修改成功','LogOperateContent'=>'ID:'.$HelpID]);
//        $this->success('此'.$this->MenuName.'已修改成功');
        $this->alert('此'.$this->MenuName.'已修改成功','back');
        exit;
    }
    //删除数据
    public function del()
    {
        if($this->request->isPost())
        {
            $this->delmore();
        }elseif($this->request->isGet()) {
            $ID = input('param.id');
            if (!empty($ID)) {
                $this->DelOneOldPic($ID, 'help', 'HelpID', 'HelpPicPath');
                $Model = new HelpModel();
                $Model->where('HelpID', $ID)->delete();
            }
            AdminLogDetail(['LogOperateTitle' => $this->MenuName . '记录删除成功', 'LogOperateContent' => 'ID:' . $ID]);
//            $this->success('此记录已删除成功');
            $this->alert('此记录已删除成功','back');
            exit;
        }
    }
    //批量删除记录
    private function delmore()
    {
        $DelID=input('post.Del/a');
        //dump($DelID);
        if(!empty($DelID))
        {
            $DelIDStr=implode(',',$DelID);
            $this->DelOneOldPic($DelIDStr,'help','HelpID','HelpPicPath');
            $Model=new HelpModel();
            $Model->where('HelpID','in',$DelIDStr)->delete();
            AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'批量删除成功','LogOperateContent'=>'ID:'.$DelIDStr]);
        }
//        $this->success('此记录批量删除成功');
        $this->alert('此记录批量删除成功','back');
        exit;
    }
    //批量排序
    public function sort()
    {
        $SortArr=input('post.Sort/a');
        //dump($SortArr);
        if(!empty($SortArr))
        {
            $TempArr=[];$SortID=[];$SortIDStr='';
            foreach ($SortArr as $key=>$val)
            {
                $SortID[]=$key;
                $TempArr[]=['HelpID'=>$key,'HelpSort'=>$val];
            }
            if(!empty($SortID)){$SortIDStr=implode(',',$SortID);}
            $Model=new HelpModel();
            $Model->saveAll($TempArr);
            AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'批量排序成功','LogOperateContent'=>'ID:'.$SortIDStr]);
        }
//        $this->success('批量排序成功');
        $this->alert('批量排序成功','back');
        exit;
    }
    //调用商品分类菜单
    private function CallHelpMenu($PID='0')
    {
        $List=Db::name('helptype')->field('TypeID,TypePID,TypePath,TypeName')->where('TypePID',$PID)->order('TypeSort Asc,TypeID Asc')->select();
        return $List;
    }
    //Ajax分类返回调用
    public function GetTypeList()
    {
        $Value=input('post.Value','');
        if(!empty($Value))
        {
            $List=$this->CallHelpMenu($Value);
            return $this->result($List,'0');
        }else{
            return $this->result('','1');
        }
    }
}