<?php
/**
 * Created by PhpStorm.
 * User: Memberistrator
 * Date: 2018/1/4
 * Time: 9:49
 */
namespace app\admin\controller;
use app\admin\model\Invite as InviteModel;
use \app\admin\model\Member as MemberModel;
class Invite extends Common
{
    private $PageCount=20;
    private $MenuName='邀请码';//栏目名称
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('MenuName',$this->MenuName);
    }
    public function index()
    {
        $UrlParam=input('get.');
        $Model=new InviteModel();
        $List=$Model->GetList($UrlParam,$this->PageCount);
		//dump($List);
        $this->assign('List',$List);
        $this->assign('UrlParam',$UrlParam);
        $this->assign('HostName','http://'.$_SERVER['HTTP_HOST']);
        return $this->fetch();
    }
    public function add()
    {
        if($this->request->isPost()){
            $Post=input('post.');
            $this->AddSave($Post);
        }else{
            $Model=new MemberModel();
            $Where=array();
            $Where['GroupID']=2;
            $Where['MemberState']=1;
            $MemberList=$Model->where($Where)->order('MemberSort Desc,MemberID Desc')->select();
            $this->assign('MemberList',$MemberList);
            return $this->fetch();
        }
    }
    //保存添加数据
    private function AddSave($Post)
    {
        if(empty($Post['InviteCode'])) $this->alert('邀请码不能为空','back');
        if(empty($Post['InviteName'])) $this->alert('推广者不能为空','back');
        $Model=new InviteModel();
        $Where=array();
        $Where['InviteMemberID']='-1';//$Post['InviteMemberID'];
        $Where['InviteCode']=$Post['InviteCode'];
        $Count=$Model->where($Where)->count();
        if(!empty($Count)) $this->alert('此邀请码已被使用','back');
        $Post['InviteMemberID']='-1';
		$Url='http://'.$_SERVER['HTTP_HOST'].'/member.php/login/index?act=reg&invite='.$Post['InviteCode'];
		$Post['Invitehost']=$Url;
        $Model->save($Post);
        $InsertID=$Model->getLastInsID();
        AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'已添加成功','LogOperateContent'=>'ID:'.$InsertID]);
//        $this->success('此'.$this->MenuName.'已添加成功');
        $this->alert('此'.$this->MenuName.'已添加成功','back');
        exit;
    }
    //删除数据
    public function del()
    {
        if($this->request->isPost()){
            $this->delmore();
        }elseif($this->request->isGet()) {
            $ID = input('param.id');
            if (!empty($ID)) {
                $Model = new InviteModel();
                $Model->where('InviteID', $ID)->delete();
            }
            AdminLogDetail(['LogOperateTitle' => $this->MenuName . '记录删除成功', 'LogOperateContent' => 'ID:' . $ID]);
            //$this->success('此记录已删除成功');
            $this->alert('此记录已删除成功','back');
            exit;
        }
    }
    //批量删除记录
    private function delmore()
    {
        $DelID=input('post.Del/a');
        //dump($DelID);
        if(!empty($DelID))
        {
            $DelIDStr=implode(',',$DelID);
            $Model=new InviteModel();
            $Model->where('InviteID','in',$DelIDStr)->delete();
            AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'批量删除成功','LogOperateContent'=>'ID:'.$DelIDStr]);
        }
        //$this->success('此记录批量删除成功');
        $this->alert('此记录批量删除成功','back');
        exit;
    }
}