<?php
/**
 * Created by PhpStorm.
 * User: Memberistrator
 * Date: 2018/1/4
 * Time: 9:49
 */
namespace app\admin\controller;
use app\admin\model\Invoice as InvoiceModel;
class Invoice extends Common
{
    private $PageCount=10;
    private $MenuName='发票';//栏目名称
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('MenuName',$this->MenuName);
    }
    public function index()
    {
        $UrlParam=input('get.');
        $Model=new InvoiceModel();
        $List=$Model->GetList($UrlParam,$this->PageCount);
        $this->assign('List',$List);
        $this->assign('UrlParam',$UrlParam);
        return $this->fetch();
    }
    public function edit()
    {
        if($this->request->isPost()){
            $Post=input('post.');
            $this->EditSave($Post);
        }else{
            $ID=input('id','','abs');
            $Model=new InvoiceModel();
            $Info=$Model->where('InvoiceID',$ID)->find();
            $Info['MemberName']=db('Member')->where('MemberID',$Info['InvoiceMemberID'])->value('MemberName');
            $this->assign('Info',$Info);
            $this->assign('InvoiceExpress',$this->GetCurrentWholeType(1));//快递名称
            $this->assign('InvoiceType',$this->GetCurrentWholeType(2));//发票类型
            $this->assign('InvoiceDetail',$this->GetCurrentWholeType(3));//发票明细
            return $this->fetch();
        }
    }
    public function EditSave($Post){
        $InvoiceID=$Post['InvoiceID'];
        $InvoiceDetail=$Post['InvoiceDetail'];
        if($InvoiceDetail!=999) $Post['InvoiceOtherContent']='';
        $Where=array();
        $Where['InvoiceID']=$InvoiceID;
        $Model=new InvoiceModel();
        if(!empty($Post['InvoiceReplyTime']))$Post['InvoiceReplyTime']=strtotime($Post['InvoiceReplyTime']);
        $Model->save($Post,$Where);
        AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'已修改成功','LogOperateContent'=>'ID:'.$InvoiceID]);
        //$this->success('此'.$this->MenuName.'已修改成功');
        $this->alert('此'.$this->MenuName.'已修改成功','back');
        exit;
    }
    //删除数据
    public function del()
    {
        if($this->request->isPost()){
            $this->delmore();
        }elseif($this->request->isGet()) {
            $ID = input('param.id');
            if (!empty($ID)) {
                $Model = new InvoiceModel();
                $Model->where('InvoiceID', $ID)->delete();
            }
            AdminLogDetail(['LogOperateTitle' => $this->MenuName . '记录删除成功', 'LogOperateContent' => 'ID:' . $ID]);
            //$this->success('此记录已删除成功');
            $this->alert('此记录已删除成功','back');
            exit;
        }
    }
    //批量删除记录
    private function delmore()
    {
        $DelID=input('post.Del/a');
        //dump($DelID);
        if(!empty($DelID))
        {
            $DelIDStr=implode(',',$DelID);
            $Model=new InvoiceModel();
            $Model->where('InvoiceID','in',$DelIDStr)->delete();
            AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'批量删除成功','LogOperateContent'=>'ID:'.$DelIDStr]);
        }
        //$this->success('此记录批量删除成功');
        $this->alert('此记录批量删除成功','back');
        exit;
    }
}