<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/7/24
 * Time: 11:23
 */
namespace app\admin\controller;
use think\Db;
use app\admin\model\Newsdynamics as NewsDynamicsModel;
class Newsdynamics extends Common
{
    private $MenuName = '优惠公告';
    private $PageCount=15;
    //公共的方法调用
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('FileSeat','/'.config('config.FileSeat').'/');
        $this->assign('MenuName', $this->MenuName);
    }
    //帮助中心列表
    public function index()
    {
        $UrlParam=input('get.');
        $this->assign('UrlParam',$UrlParam);
        $Keyword=input('keyword','');
        $Model=new NewsDynamicsModel();
        $List = $Model->GetList($this->PageCount,$Keyword);
        $this->assign('List', $List);
        return $this->fetch();
    }
    //帮助中心添加
    public function add()
    {
        if($this->request->isPost())
        {
            $Post=input('post.');
            $this->AddSave($Post);
        }else{
            //调取商品级联菜单
            $NewsTypeListOne=$this->CallNewsMenu('0');
            $this->assign('NewsTypeListOne',$NewsTypeListOne);
            return $this->fetch();
        }
    }
    //保存添加数据
    private function AddSave($Post)
    {
        //对分类数据处理
        if(!empty($Post['NewsType']))
        {
            $NewsType=array_filter($Post['NewsType']);
            $NewsType=end($NewsType);
            //dump($NewsType);
            if(!empty($NewsType)){
                $NewsTypeArr=explode('_',$NewsType);
                $Post['NewsTypeID']=$NewsTypeArr[0];
                $Post['NewsTypePath']=$NewsTypeArr[1];
            }
        }
        unset($Post['NewsType']);
        $Model=new NewsDynamicsModel();
        //图片上传
        $PicPath=$this->OneUpload('NewsPicPath');
        if(!empty($PicPath)){
            $Post['NewsPicPath']=$PicPath;
        }
        $Model->save($Post);
        $InsertID=$Model->getLastInsID();
        AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'已添加成功','LogOperateContent'=>'ID:'.$InsertID]);
//        $this->success('此'.$this->MenuName.'已添加成功');
        $this->alert('此'.$this->MenuName.'已添加成功','back');
        exit;
    }
    //数据修改
    public function edit()
    {
        if($this->request->isPost())
        {
            $Post=input('post.');
            $this->EditSave($Post);
        }else{
            $ID=input('param.id','','abs');
            $Model=new NewsDynamicsModel();
            $Info=$Model->get($ID);
            $this->assign('Info',$Info);
            //获取联级菜单数据
            $GetTypeCascadeList=$this->GetTypeCascadeList('News',$Info['NewsTypePath'],'newsdynamicstype');
            $this->assign('GetTypeCascadeList',$GetTypeCascadeList);
            return $this->fetch();
        }
    }
    //保存修改数据
    private function EditSave($Post)
    {
        $NewsID=$Post['NewsID'];
        //对分类数据处理
        if(!empty($Post['NewsType']))
        {
            $NewsType=array_filter($Post['NewsType']);
            $NewsType=end($NewsType);
            //dump($NewsType);
            if(!empty($NewsType)){
                $NewsTypeArr=explode('_',$NewsType);
                $Post['NewsTypeID']=$NewsTypeArr[0];
                $Post['NewsTypePath']=$NewsTypeArr[1];
            }
        }
        unset($Post['NewsType']);
        //图片上传
        $PicPath=$this->OneUpload('NewsPicPath');
        if(!empty($PicPath)){
            $this->DelOneOldPic($NewsID,'news','NewsID','NewsPicPath');//先删除
            $Post['NewsPicPath']=$PicPath;
        }
        $Where=[];
        $Where['NewsID']=$NewsID;
        $Model=new NewsDynamicsModel();
        $Model->save($Post,$Where);
        AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'已修改成功','LogOperateContent'=>'ID:'.$NewsID]);
//        $this->success('此'.$this->MenuName.'已修改成功');
        $this->alert('此'.$this->MenuName.'已修改成功','back');
        exit;
    }
    //删除数据
    public function del()
    {
        if($this->request->isPost())
        {
            $this->delmore();
        }elseif($this->request->isGet()) {
            $ID = input('param.id');
            if (!empty($ID)) {
                $this->DelOneOldPic($ID, 'news', 'NewsID', 'NewsPicPath');
                $Model = new NewsDynamicsModel();
                $Model->where('NewsID', $ID)->delete();
            }
            AdminLogDetail(['LogOperateTitle' => $this->MenuName . '记录删除成功', 'LogOperateContent' => 'ID:' . $ID]);
//            $this->success('此记录已删除成功');
            $this->alert('此记录已删除成功','back');
            exit;
        }
    }
    //批量删除记录
    private function delmore()
    {
        $DelID=input('post.Del/a');
        //dump($DelID);
        if(!empty($DelID))
        {
            $DelIDStr=implode(',',$DelID);
            $this->DelOneOldPic($DelIDStr,'news','NewsID','NewsPicPath');
            $Model=new NewsDynamicsModel();
            $Model->where('NewsID','in',$DelIDStr)->delete();
            AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'批量删除成功','LogOperateContent'=>'ID:'.$DelIDStr]);
        }
//        $this->success('此记录批量删除成功');
        $this->alert('此记录批量删除成功','back');
        exit;
    }
    //批量排序
    public function sort()
    {
        $SortArr=input('post.Sort/a');
        //dump($SortArr);
        if(!empty($SortArr))
        {
            $TempArr=[];$SortID=[];$SortIDStr='';
            foreach ($SortArr as $key=>$val)
            {
                $SortID[]=$key;
                $TempArr[]=['NewsID'=>$key,'NewsSort'=>$val];
            }
            if(!empty($SortID)){$SortIDStr=implode(',',$SortID);}
            $Model=new NewsDynamicsModel();
            $Model->saveAll($TempArr);
            AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'批量排序成功','LogOperateContent'=>'ID:'.$SortIDStr]);
        }
//        $this->success('排序更新成功');
        $this->alert('排序更新成功','back');
        exit;
    }
    //调用商品分类菜单
    private function CallNewsMenu($PID='0')
    {
        $List=Db::name('newsdynamicstype')->field('TypeID,TypePID,TypePath,TypeName')->where('TypePID',$PID)->order('TypeSort Asc,TypeID Asc')->select();
        return $List;
    }
    //Ajax分类返回调用
    public function GetTypeList()
    {
        $Value=input('post.Value','');
        if(!empty($Value))
        {
            $List=$this->CallNewsMenu($Value);
            return $this->result($List,'0');
        }else{
            return $this->result('','1');
        }
    }
}