<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/7/24
 * Time: 11:23
 */
namespace app\admin\controller;
use think\Db;
use app\admin\model\Poster as PosterModel;
class Poster extends Common
{
    private $MenuName = '广告';
    private $PageCount=15;
    //公共的方法调用
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('FileSeat','/'.config('config.FileSeat').'/');
        $this->assign('MenuName', $this->MenuName);
    }
    //广告列表
    public function index()
    {
        $UrlParam=input('get.');
        $this->assign('UrlParam',$UrlParam);
        $UrlParam=input('get.');
        $Model=new PosterModel();
        $List=$Model->GetList($UrlParam,$this->PageCount);
        $this->assign('List',$List);
        return $this->fetch();
    }
    //广告添加
    public function add()
    {
        if($this->request->isPost())
        {
            $Post=input('post.');
            $this->AddSave($Post);
        }else{
            //获取商品分类数据
            $this->assign('GetPosterTypeList',$this->GetSeatTypeList('postertype','0'));
            return $this->fetch();
        }
    }
    //保存添加数据
    private function AddSave($Post)
    {
        //对分类数据处理
        if(!empty($Post['PosterType']))
        {
            $PosterType=array_filter($Post['PosterType']);
            $PosterType=end($PosterType);
            //dump($PosterType);
            if(!empty($PosterType)){
                $PosterTypeArr=explode('_',$PosterType);
                $Post['PosterTypeID']=$PosterTypeArr[0];
                $Post['PosterTypePath']=$PosterTypeArr[1];
            }
        }
        unset($Post['PosterType']);
        $Model=new PosterModel();
        //图片上传
        $PicPath=$this->OneUpload('PosterPicPath');
        if(!empty($PicPath)){
            $Post['PosterPicPath']=$PicPath;
        }
        $Model->save($Post);
        $InsertID=$Model->getLastInsID();
        AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'已添加成功','LogOperateContent'=>'ID:'.$InsertID]);
//        $this->success('此'.$this->MenuName.'已添加成功');
        $this->alert('此'.$this->MenuName.'已添加成功','back');
        exit;
    }
    //数据修改
    public function edit()
    {
        if($this->request->isPost())
        {
            $Post=input('post.');
            $this->EditSave($Post);
        }else{
            $ID=input('param.id','','abs');
            $Model=new PosterModel();
            $Info=$Model->get($ID);
            $this->assign('Info',$Info);
            //获取联级菜单数据
            $GetTypeCascadeList=$this->GetTypeCascadeList('Poster',$Info['PosterTypePath'],'postertype');
            $this->assign('GetTypeCascadeList',$GetTypeCascadeList);
            return $this->fetch();
        }
    }
    //保存修改数据
    private function EditSave($Post)
    {
        $PosterID=$Post['PosterID'];
        //对分类数据处理
        if(!empty($Post['PosterType']))
        {
            $PosterType=array_filter($Post['PosterType']);
            $PosterType=end($PosterType);
            //dump($PosterType);
            if(!empty($PosterType)){
                $PosterTypeArr=explode('_',$PosterType);
                $Post['PosterTypeID']=$PosterTypeArr[0];
                $Post['PosterTypePath']=$PosterTypeArr[1];
            }
        }
        unset($Post['PosterType']);
        //图片上传
        $PicPath=$this->OneUpload('PosterPicPath');
        if(!empty($PicPath)){
            $this->DelOneOldPic($PosterID,'poster','PosterID','PosterPicPath');//先删除
            $Post['PosterPicPath']=$PicPath;
        }
        $Where=[];
        $Where['PosterID']=$PosterID;
        $Model=new PosterModel();
        $Model->save($Post,$Where);
        AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'已修改成功','LogOperateContent'=>'ID:'.$PosterID]);
//        $this->success('此'.$this->MenuName.'已修改成功');
        $this->alert('此'.$this->MenuName.'已修改成功','back');
        exit;
    }
    //删除数据
    public function del()
    {
        if($this->request->isPost())
        {
            $this->delmore();
        }elseif($this->request->isGet()) {
            $ID = input('param.id');
            if (!empty($ID)) {
                $this->DelOneOldPic($ID, 'poster', 'PosterID', 'PosterPicPath');
                $this->DelOneOldPic($ID, 'poster', 'PosterID', 'BgPosterPicPath');
                $Model = new PosterModel();
                $Model->where('PosterID', $ID)->delete();
            }
            AdminLogDetail(['LogOperateTitle' => $this->MenuName . '记录删除成功', 'LogOperateContent' => 'ID:' . $ID]);
//            $this->success('此记录已删除成功');
            $this->alert('此记录已删除成功','back');
            exit;
        }
    }
    //批量删除记录
    private function delmore()
    {
        $DelID=input('post.Del/a');
        //dump($DelID);
        if(!empty($DelID))
        {
            $DelIDStr=implode(',',$DelID);
            $this->DelOneOldPic($DelIDStr,'poster','PosterID','PosterPicPath');
            $this->DelOneOldPic($DelIDStr,'poster','PosterID','BgPosterPicPath');
            $Model=new PosterModel();
            $Model->where('PosterID','in',$DelIDStr)->delete();
            AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'批量删除成功','LogOperateContent'=>'ID:'.$DelIDStr]);
        }
//        $this->success('此记录批量删除成功');
        $this->alert('此记录批量删除成功','back');
        exit;
    }
    //批量排序
    public function sort()
    {
        $SortArr=input('post.Sort/a');
        //dump($SortArr);
        if(!empty($SortArr))
        {
            $TempArr=[];$SortID=[];$SortIDStr='';
            foreach ($SortArr as $key=>$val)
            {
                $SortID[]=$key;
                $TempArr[]=['PosterID'=>$key,'PosterSort'=>$val];
            }
            if(!empty($SortID)){$SortIDStr=implode(',',$SortID);}
            $Model=new PosterModel();
            $Model->saveAll($TempArr);
            AdminLogDetail(['LogOperateTitle'=>$this->MenuName.'批量排序成功','LogOperateContent'=>'ID:'.$SortIDStr]);
        }
//        $this->success('排序更新成功');
        $this->alert('排序更新成功','back');
        exit;
    }
}