<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/5
 * Time: 11:21
 */
namespace app\member\controller;
use app\member\model\Media as MediaModel;
use think\Db;
use think\Request;
use think\Loader;
class Media extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('MediaWebNameID',GetCurrentWholeType(18));//	频道类型
        $this->assign('MediaIndustryID',GetCurrentWholeType(35));//综合门户媒体
        $this->assign('MediaCityID',GetCityTypeList('0'));//覆盖区域
        $this->assign('MediaInLevelID',GetCurrentWholeType(110));//入口级别
        $this->assign('MediaUrlTypeID',GetCurrentWholeType(59));//链接类型
        $this->assign('MediaSpeedID',GetCurrentWholeType(66));//发稿速度
        $this->assign('MediaNewsSourceID',GetCurrentWholeType(73));//新闻源
        $this->assign('MediaCanSendID',GetCurrentWholeType(76));//周末可发
        $this->assign('MediaSpecialIndustryID',GetCurrentWholeType(79));//特别行业
        $this->assign('MediaSituationID',GetCurrentWholeType(85));//收录情况
        $this->assign('MediaComputerWeightID',GetCurrentWholeType(88));//电脑权重
        $this->assign('MediaMobileWeightID',GetCurrentWholeType(99));//移动权重
		$this->assign('MediaMobileWeightID',GetCurrentWholeType(99));//移动权重
		$this->assign('MediaPrice',MpriceNum());//媒体价格
		parent::checktype();
    }
    public function index()
    {
        session('MenuCookie','2');
        return view();
    }
    //获取媒体列表
    public function getlist()
    {
        $UrlParam=input();
        $this->assign('UrlParam',$UrlParam);
        $MemberInfo=db('member')->where('MemberID',$this->MemberID)->find();
        $Where=array();
         $Model=new \app\member\model\Media();
        $List=$Model->GetMediaList($UrlParam,$Where,20,$MemberInfo,$this->AgencySiteInfo['MemberID'],$this->AgencySiteInfo,$MemberInfo['MemberPriceType']-115);
        $_SESSION['UrlParam']=$UrlParam;
        $Back=array();
        $Back['code']='0';
        $Back['count']=$List->total();
        $Back['msg']='媒体列表';
        $Back['data']=$List->items();
        return json($Back);
    }
    //导出Excel
    public function exportexcel()
    {
        $UrlParam=input();
        $MemberInfo=db('member')->where('MemberID',$this->MemberID)->find();
        $name='媒体价格';
        $Model=new \app\member\model\Media();
        $Info=$Model->GetMediaListFull($UrlParam,[],$this->MemberID,$this->AgencySiteInfo['MemberID']);
        if(!empty($Info)){
            if(sizeof($Info)>1000){
                $this->alert('导出的数据不能超过1000条','back');
                exit;
            }
            if(!empty($UrlParam['jump']) && $UrlParam['jump']=='yes') return json('0');
            //获取标题
            $TitleInfo=GetExportTitle('memmerdia');
            excelExport($name,$TitleInfo,$Info);
        }else{
            $this->alert('导出的数据为空','back');
            exit;
        }
    }
    //收藏
    public function collect(){
        $ID=input('MediaID','','intval');
        $MemberID=$this->MemberID;
        if($MemberID<=0) $this->result('','1','请先登录，再加入收藏');
        $Where=array();
        $Where['CollectMemberID']=$MemberID;
        $Where['CollectGoodsID']=$ID;
        $Where['CollectAgencyDomainID']=$this->AgencySiteInfo['MemberID'];
		$Where['ctype']=1;
        $count=Db::name('collect')->where($Where)->count();
        if($count>0) {
            //$this->result('','2','您已收藏');
            Db::name('collect')->where($Where)->delete();
            $this->result('','2','您已取消');
        }
        $Data=array();
        $Data['CollectMemberID']=$MemberID;
        $Data['CollectGoodsID']=$ID;
        $Data['CollectAgencyDomainID']=$this->AgencySiteInfo['MemberID'];
        $Data['CollectTime']=time();
        Db::name('collect')->insert($Data);
        $this->result('','0','收藏成功');
    }
	public function caselinks(){
		$data=array();
		$data=input();
        $data1['MessageMemberID'] = $this->MemberID;
		//$data1['mid'] = $data['id'];
		if($data['id']){
			$media = Db::name('media')->where('MediaID',$data['id'])->find();
			$name=$media['MediaTitle'];
		}else{
			return ['code'=>'201','msg'=>'反馈失败'];
		}
		$data1['MessageContent'] = '媒体案例链接反馈【'.$name.'=ID:'.$data['id'].'】';
        $data1['MessageTime'] =time();
		$info=Db::name('message')->insert($data1);
		return ['code'=>'200','msg'=>'感谢您的反馈，我们将立即处理！'];
	}
	
}