<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/5
 * Time: 11:21
 */
namespace app\member\controller;
use app\member\model\Wemedia as WemediaModel;
use think\Db;
use think\Request;
use think\Loader;
class Wemedia extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
		parent::checktype();
    }
    public function index()
    {
        session('MenuCookie','2');
      // $str = controller('common/Common')->media();
       // $this->assign('html',$str);
		$this->assign('MediaWebNameID',GetCurrentWholeType(157));//	平台
        $this->assign('MediaIndustryID',GetCurrentWholeType(160));//行业类型
        $this->assign('MediaCityID',GetCityTypeList('0'));//覆盖区域
		$this->assign('fennumid',FanNum());//粉丝数
        $this->assign('MediaRedID',ReadNum());//阅读数
		$this->assign('pricenum',PriceNum());
		$this->assign('auth',AuthNum());
		$this->assign('can_video',Can_video());
		$this->assign('weekend_publish',Weekend_publish());
        return view('wemedia');
    }
    //获取媒体列表
    public function getlist()
    {
        $UrlParam=input('get.');
        $this->assign('UrlParam',$UrlParam);
        $MemberInfo=db('member')->where('MemberID',$this->MemberID)->find();
        $Where=array();
        //$Where['agency_id']=$this->MemberID;
        $Model=new WemediaModel;
        $List=$Model->GetMediaList($UrlParam,$Where,20,$MemberInfo,$this->AgencySiteInfo['MemberID'],$this->AgencySiteInfo,$MemberInfo['MemberPriceType']-115);
        $_SESSION['UrlParam']=$UrlParam;
        $Back=array();
        $Back['code']='0';
        $Back['count']=$List->total();
        $Back['msg']='自媒体列表';
        $Back['data']=$List->items();
        return json($Back);
    }
    //导出Excel
    public function exportexcel()
    { 
		set_time_limit(0);
        $UrlParam=input();
        $MemberInfo=db('member')->where('MemberID',$this->MemberID)->find();
        $name='自媒体价格';
        $Model=new WemediaModel;
        $Info=$Model->GetWemediaListFull($UrlParam,[],$this->MemberID,$this->AgencySiteInfo['MemberID']);
		
        if(!empty($Info)){
			/*
            if(sizeof($Info)>1000){
                $this->alert('导出的数据不能超过1000条','back');
                exit;
            }
			*/
			  foreach($Info as $key=>$val) {
                if(!empty($val['MediaWebNameID']))
                {
                    $TypeName=db('wholetype')->where('TypeID',$val['MediaWebNameID'])->value('TypeName');
                    $Info[$key]['MediaWebNameIDNew']=$TypeName;
                }else{
                    $Info[$key]['MediaWebNameIDNew']='';
                }
                if(!empty($val['MediaIndustryID']))
                {
                    $TypeName=db('wholetype')->where('TypeID',$val['MediaIndustryID'])->value('TypeName');
                    $Info[$key]['MediaIndustryIDNew']=$TypeName;
                }else{
                    $Info[$key]['MediaIndustryIDNew']='';
                }
                if(!empty($val['MediaCityID']))
                {
                    $TypeName=db('citytype')->where('TypeID',$val['MediaCityID'])->value('TypeName');
                    $Info[$key]['MediaCityIDNew']=$TypeName;
                }else{
                    $Info[$key]['MediaCityIDNew']='';
                }
            }

            if(!empty($UrlParam['jump']) && $UrlParam['jump']=='yes') return json('0');
            //获取标题
            $TitleInfo=GetExportTitle('wemerdia');
            excelExport($name,$TitleInfo,$Info);
        }else{
            $this->alert('导出的数据为空','back');
            exit;
        }
    }
    //收藏
    public function collect(){
        $ID=input('MediaID','','intval');
        $MemberID=$this->MemberID;
        if($MemberID<=0) $this->result('','1','请先登录，再加入收藏');
        $Where=array();
        $Where['CollectMemberID']=$MemberID;
        $Where['CollectGoodsID']=$ID;
        $Where['CollectAgencyDomainID']=$this->AgencySiteInfo['MemberID'];
		$Where['ctype']=2;
        $count=Db::name('collect')->where($Where)->count();
        if($count>0) {
            //$this->result('','2','您已收藏');
            Db::name('collect')->where($Where)->delete();
            $this->result('','2','您已取消');
        }
        $Data=array();
        $Data['CollectMemberID']=$MemberID;
        $Data['CollectGoodsID']=$ID;
        $Data['CollectAgencyDomainID']=$this->AgencySiteInfo['MemberID'];
        $Data['CollectTime']=time();
		$Data['ctype']=2;
        Db::name('collect')->insert($Data);
        $this->result('','0','收藏成功');
    }
	public function caselinks(){
		$data=array();
		$data=input();
        $data1['MessageMemberID'] = $this->MemberID;
		//$data1['mid'] = $data['id'];
		if($data['id']){
			$media = Db::name('wemedia')->where('MediaID',$data['id'])->find();
			$name=$media['MediaTitle'];
		}else{
			return ['code'=>'201','msg'=>'反馈失败'];
		}
		$data1['MessageContent'] = '自媒体案例链接反馈【'.$name.'=ID:'.$data['id'].'】';
        $data1['MessageTime'] =time();
		$info=Db::name('message')->insert($data1);
		return ['code'=>'200','msg'=>'感谢您的反馈，我们将立即处理！'];
	}
}