<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/7/14
 * Time: 11:19
 */
return [
    'media'=>[
        'MediaWebNameIDNew'=>'媒体平台',
        'MediaIndustryIDNew'=>'行业分类',
        'MediaCityIDNew'=>'媒体地区',
        'MediaTitle'=>'媒体名称',
        'MediaWebPrice'=>'价格',
        //'MediaMemberPrice1'=>'游客价格',
        //'MediaMemberPrice2'=>'A级价格',
        //'MediaMemberPrice3'=>'B级价格',
        //'MediaMemberPrice4'=>'C级价格',
        //'MediaTime'=>'添加时间',
    ],
	'wemerdia'=>[
		'MediaWebNameIDNew'=>'媒体平台',
        'MediaIndustryIDNew'=>'行业分类',
        'MediaCityIDNew'=>'媒体地区',
        'MediaTitle'=>'媒体名称',
		'MediaCaseUrl'=>'案例链接',
		'MediaInUrl'=>'入口',
		'fans_num'=>'粉丝数',
		'read_num'=>'阅读数',
        'price'=>'价格',
        'MediaContent'=>'备注说明'
    ],

	'videomerdia'=>[
		'pdlx'=>'媒体平台',
        'hyfl'=>'行业分类',
        'city'=>'媒体地区',
        'MediaTitle'=>'媒体名称',
		'MediaInUrl'=>'主页链接',
		'Age'=>'博主年龄',
		'Gender'=>'性别',
		'pricetitle'=>'发布类型',
        'price'=>'价格',
		'Fennumid'=>'粉丝数',
		'Numbercount'=>'点赞总数',
        'MediaContent'=>'备注说明'
    ],

    'agencymedia'=>[
        'pdlx'=>'频道类型',
        'city'=>'所在区域',
        'MediaTitle'=>'媒体名称',
        'MediaInUrl'=>'入口链接',
        'MediaCaseUrl'=>'案例链接',
        'ljlx'=>'链接类型',
        'price'=>'价格',
        'cgl'=>'出稿率',
        'dnqz'=>'电脑权重',
        'ydqz'=>'移动权重',
        'xwy'=>'新闻源',
        'MediaContent'=>'备注说明'
    ],
    'memmerdia'=>[
        'pdlx'=>'频道类型',
        'city'=>'所在区域',
        'MediaTitle'=>'媒体名称',
        'MediaInUrl'=>'入口链接',
        'MediaCaseUrl'=>'案例链接',
        'ljlx'=>'链接类型',
        'price'=>'价格',
        'cgl'=>'出稿率',
        'dnqz'=>'电脑权重',
        'ydqz'=>'移动权重',
        'xwy'=>'新闻源',
        'MediaContent'=>'备注说明'
    ],
    'memberorder'=>[
        'order_number'=>'订单号',
        'article_title'=>'文章标题',
        'fabu_site'=>'发布网址',
        'MediaTitle'=>'媒体名称',
        'order_money'=>'文章费用',
        'order_statename'=>'发布状态',
        'order_stateaffirmtime'=>'提交时间',
        'order_statereleasetime'=>'发布时间',
    ],
	'videoorder'=>[
        'order_number'=>'订单号',
        'article_title'=>'文章标题',
        'fabu_site'=>'发布网址',
		'pricetitle'=>'发布类型',
		'pdlx'=>'媒体平台',
        'MediaTitle'=>'媒体名称',
        'order_money'=>'文章费用',
        'order_statename'=>'发布状态',
        'order_stateaffirmtime'=>'提交时间',
        'order_statereleasetime'=>'发布时间',
    ],
    'agencyorder'=>[
        'order_number'=>'订单号',
        'MemberName'=>'用户名',
        'article_title'=>'文章标题',
        'article_website'=>'发布网址',
        'MediaTitle'=>'媒体名称',
        'order_money'=>'文章费用',
        'order_state'=>'发布状态',
        'order_time'=>'提交时间',
        'release_time'=>'发布时间',
    ],
    'agencymediaorder'=>[
        'order_number'=>'订单号',
        'article_title'=>'文章标题',
        //'article_website'=>'发布网址',
        'fabu_site'=>'发布网址',
        'MediaTitle'=>'媒体名称',
        'order_money'=>'文章费用',
        'order_state'=>'发布状态',
        'order_time'=>'提交时间',
        'release_time'=>'发布时间',
    ],
];